---
- name: Installation of wordpress
  become: true
  hosts: all
  roles: 
    - lamp
  tasks:
    - name: "Wordpress - Downloading Archive File"
      get_url:
        url: https://wordpress.org/wordpress-5.8.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: "Wordpress - Extracting Wordpress"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true

    - name: "Wordpress - Copying Contents To Docroot"
      copy:
        src: /tmp/wordpress/
        dest: /var/www/html/{{ domain_name }}/
        remote_src: true
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"


    - name: "Wordpress - Creating wp-config.php"
      template:
        src: wp-config.template
        dest: "/var/www/html/{{ domain_name }}/wp-config.php"
        owner: "{{ httpd_user }}"


